# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo01
	pod 'SVProgressHUD'
	pod 'Masonry'
end
